"""Predictor + parameter registries referencing INDICATOR_ENGINE_V1 IDs."""
from __future__ import annotations

from typing import Any

PARAMETER_REGISTRY: dict[str, dict[str, Any]] = {
    "PRED_DMA_3X3_CROSS_UP_V1": {
        "predictor_id": "DMA_CROSS_UP",
        "indicator_parameter_set_id": "DMA_3X3_V1",
        "period": 3,
        "display_shift": 3,
        "direction": "UP",
    },
    "PRED_DMA_3X3_CROSS_DOWN_V1": {
        "predictor_id": "DMA_CROSS_DOWN",
        "indicator_parameter_set_id": "DMA_3X3_V1",
        "period": 3,
        "display_shift": 3,
        "direction": "DOWN",
    },
    "PRED_DMA_7X5_CROSS_UP_V1": {
        "predictor_id": "DMA_CROSS_UP",
        "indicator_parameter_set_id": "DMA_7X5_V1",
        "period": 7,
        "display_shift": 5,
        "direction": "UP",
    },
    "PRED_DMA_7X5_CROSS_DOWN_V1": {
        "predictor_id": "DMA_CROSS_DOWN",
        "indicator_parameter_set_id": "DMA_7X5_V1",
        "period": 7,
        "display_shift": 5,
        "direction": "DOWN",
    },
    "PRED_DMA_25X5_CROSS_UP_V1": {
        "predictor_id": "DMA_CROSS_UP",
        "indicator_parameter_set_id": "DMA_25X5_V1",
        "period": 25,
        "display_shift": 5,
        "direction": "UP",
    },
    "PRED_DMA_25X5_CROSS_DOWN_V1": {
        "predictor_id": "DMA_CROSS_DOWN",
        "indicator_parameter_set_id": "DMA_25X5_V1",
        "period": 25,
        "display_shift": 5,
        "direction": "DOWN",
    },
    "PRED_RSI_14_30_V1": {
        "predictor_id": "RSI_LEVEL",
        "indicator_parameter_set_id": "RSI_14_V1",
        "period": 14,
        "level": 30.0,
    },
    "PRED_RSI_14_50_V1": {
        "predictor_id": "RSI_LEVEL",
        "indicator_parameter_set_id": "RSI_14_V1",
        "period": 14,
        "level": 50.0,
    },
    "PRED_RSI_14_70_V1": {
        "predictor_id": "RSI_LEVEL",
        "indicator_parameter_set_id": "RSI_14_V1",
        "period": 14,
        "level": 70.0,
    },
    "PRED_RSI_14_CROSS_UP_30_V1": {
        "predictor_id": "RSI_CROSS_UP",
        "indicator_parameter_set_id": "RSI_14_V1",
        "period": 14,
        "level": 30.0,
        "cross": "UP",
    },
    "PRED_RSI_14_CROSS_DOWN_70_V1": {
        "predictor_id": "RSI_CROSS_DOWN",
        "indicator_parameter_set_id": "RSI_14_V1",
        "period": 14,
        "level": 70.0,
        "cross": "DOWN",
    },
    "PRED_MACD_12_26_9_SIGNAL_CROSS_UP_V1": {
        "predictor_id": "MACD_SIGNAL_CROSS_UP",
        "indicator_parameter_set_id": "MACD_12_26_9_V1",
        "fast": 12,
        "slow": 26,
        "signal": 9,
        "mode": "SIGNAL_CROSS_UP",
    },
    "PRED_MACD_12_26_9_SIGNAL_CROSS_DOWN_V1": {
        "predictor_id": "MACD_SIGNAL_CROSS_DOWN",
        "indicator_parameter_set_id": "MACD_12_26_9_V1",
        "fast": 12,
        "slow": 26,
        "signal": 9,
        "mode": "SIGNAL_CROSS_DOWN",
    },
    "PRED_MACD_12_26_9_HIST_ZERO_V1": {
        "predictor_id": "MACD_HIST_ZERO",
        "indicator_parameter_set_id": "MACD_12_26_9_V1",
        "fast": 12,
        "slow": 26,
        "signal": 9,
        "mode": "HIST_ZERO",
    },
    "PRED_STOCH_14_K_20_POINT_V1": {
        "predictor_id": "STOCH_K_LEVEL_POINT_BAR",
        "indicator_parameter_set_id": "STOCH_14_3_3_V1",
        "k_period": 14,
        "level": 20.0,
    },
    "PRED_STOCH_14_K_80_POINT_V1": {
        "predictor_id": "STOCH_K_LEVEL_POINT_BAR",
        "indicator_parameter_set_id": "STOCH_14_3_3_V1",
        "k_period": 14,
        "level": 80.0,
    },
    "PRED_STOCH_K_CROSS_D_UP_V1": {
        "predictor_id": "STOCH_K_CROSS_D",
        "indicator_parameter_set_id": "STOCH_14_3_3_V1",
        "direction": "UP",
    },
    "PRED_SMA_20_CROSS_UP_V1": {
        "predictor_id": "SMA_CROSS_UP",
        "indicator_parameter_set_id": "SMA_20_V1",
        "period": 20,
        "direction": "UP",
    },
    "PRED_EMA_20_CROSS_UP_V1": {
        "predictor_id": "EMA_CROSS_UP",
        "indicator_parameter_set_id": "EMA_20_V1",
        "period": 20,
        "direction": "UP",
    },
    "PRED_WMA_20_CROSS_UP_V1": {
        "predictor_id": "WMA_CROSS_UP",
        "indicator_parameter_set_id": "WMA_20_V1",
        "period": 20,
        "direction": "UP",
    },
    "PRED_PROJECT_OSC_20_50_2_V1": {
        "predictor_id": "PROJECT_OSCILLATOR_PREDICTOR_V1",
        "indicator_parameter_set_id": "SMA_20_V1",
        "ma_period": 20,
        "lookback": 50,
        "k_std": 2.0,
        "preset_class": "PROJECT_EXPERIMENTAL",
    },
    "PRED_BOLLINGER_FEASIBILITY_V1": {
        "predictor_id": "BOLLINGER_BAND_INVERSE",
        "indicator_parameter_set_id": "BOLLINGER_20_2_V1",
        "status": "UNSUPPORTED_V1",
    },
    "PRED_DNO_OB_V1": {
        "predictor_id": "DNO_OB_OS_PREDICTOR_OB",
        "indicator_parameter_set_id": "DNO_REF_N7_V1",
        "period": 7,
        "target_level": 2.0,
    },
    "PRED_DNO_OS_V1": {
        "predictor_id": "DNO_OB_OS_PREDICTOR_OS",
        "indicator_parameter_set_id": "DNO_REF_N7_V1",
        "period": 7,
        "target_level": -2.0,
    },
}

PREDICTOR_REGISTRY: list[dict[str, Any]] = [
    {"predictor_id": "DMA_CROSS_UP", "indicator_family": "DMA", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "DMA_CROSS_DOWN", "indicator_family": "DMA", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "RSI_LEVEL", "indicator_family": "RSI", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "RSI_CROSS_UP", "indicator_family": "RSI", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "RSI_CROSS_DOWN", "indicator_family": "RSI", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "MACD_SIGNAL_CROSS_UP", "indicator_family": "MACD", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "MACD_SIGNAL_CROSS_DOWN", "indicator_family": "MACD", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "MACD_HIST_ZERO", "indicator_family": "MACD", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "STOCH_K_LEVEL_POINT_BAR", "indicator_family": "STOCHASTIC", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "POINT_BAR_H_EQ_L_EQ_X", "causal_eligible": "YES"},
    {"predictor_id": "STOCH_K_CROSS_D", "indicator_family": "STOCHASTIC", "solution_method": "REQUIRES_INTRABAR_ASSUMPTION", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "REQUIRED", "causal_eligible": "PARTIAL"},
    {"predictor_id": "SMA_CROSS_UP", "indicator_family": "SMA", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "EMA_CROSS_UP", "indicator_family": "EMA", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "WMA_CROSS_UP", "indicator_family": "WMA", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "PROJECT_OSCILLATOR_PREDICTOR_V1", "indicator_family": "PROJECT_OSC", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "DNO_OB_OS_PREDICTOR_OB", "indicator_family": "DNO", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "DNO_OB_OS_PREDICTOR_OS", "indicator_family": "DNO", "solution_method": "EXACT_ANALYTIC", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "NONE", "causal_eligible": "YES"},
    {"predictor_id": "BOLLINGER_BAND_INVERSE", "indicator_family": "BOLLINGER", "solution_method": "UNSUPPORTED_V1", "hypothetical_input_type": "NEXT_BAR_CLOSE", "intrabar_assumption": "N/A", "causal_eligible": "NO"},
]

SCHEMA_COLUMNS = [
    ("predictor_engine_version", "IDENTITY", "Engine version"),
    ("predictor_id", "IDENTITY", "Predictor type"),
    ("parameter_set_id", "IDENTITY", "Predictor parameter set"),
    ("source_timeframe", "IDENTITY", "TF"),
    ("decision_time", "CAUSAL_TIME", "Decision timestamp"),
    ("calculated_at", "CAUSAL_TIME", "Last closed bar"),
    ("available_at", "CAUSAL_TIME", "Earliest causal use"),
    ("predicted_trigger_price", "OUTPUT", "Solved X or null"),
    ("solution_status", "DIAGNOSTIC", "EXACT_ANALYTIC|..."),
    ("hypothetical_input_type", "IDENTITY", "NEXT_BAR_CLOSE"),
    ("distance_*", "OUTPUT", "Distance features"),
]
