"""OSCILLATOR-PREDICTOR-HISTORICAL-EVENT-STUDY-1 version metadata."""

STUDY_VERSION = "OSCILLATOR_PREDICTOR_HISTORICAL_EVENT_STUDY_V1"
WIP_ID = "OSCILLATOR-PREDICTOR-HISTORICAL-EVENT-STUDY-1"
PREDICTOR_AUTHORITY_COMMIT = "6b1e34e4dffb469e0b9392c33d20e5689a2cdfe2"
